### ISSUE TITLE
Clarification for input_mapping

### ISSUE THREAD

**Issue by RAbraham** [scallop-lang/scallop#34]
Hi,
For the Learning MNIST Sum-2 example, in the [documentation](https://www.scallop-lang.org/tutorial.html#section-11),  it's ` input_mapping=[(i,) for i in range(10)]`
```python
    self.scl_ctx.add_relation("digit_1", (int,), input_mapping=[(i,) for i in range(10)])
```
while in the attached source code, it's `input_mapping=list(range(10))`

```python
        self.scl_ctx.add_relation("digit_1", int, input_mapping=list(range(10)))

```

I assume they are the same but I just wanted to double check.

Regards,
Rajiv

**Comment by Liby99** [comment]
These are the same and specifically the second one is a "syntax sugar".

If you allow me to go into a bit more detail:

```
[(i,) for i in range(10)] ==> [(0,), (1,), (2,), ..., (9,)]
list(range(10)) ==> [0, 1, 2, ..., 9]
```

So the technical difference is that the first notation specifies list of arity-1 tuples, and the second one specifies list of integers. Afterall, scallop accepts tuples so the first notation is more standardized. However for ergonomics, we allow the second syntax because simple integer values (as well as booleans, strings, etc) will be converted to arity-1 tuples.

**Comment by RAbraham** [comment]
Nice! I'm appreciating all the small conveniences that the lib api offers. Thanks!
